### ISSUE TITLE
FATAL EXCEPTION when capture

### ISSUE THREAD

**Issue by langlang2012** [anthorlop/VideoRecorderCamera#1]
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime: FATAL EXCEPTION: main
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime: Process: es.anthorlop.camera, PID: 26986
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime: java.lang.IllegalArgumentException: Unsupported quality level: 8
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.media.CamcorderProfile.get(CamcorderProfile.java:345)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.media.CamcorderProfile.get(CamcorderProfile.java:294)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at es.anthorlop.camera.activities.CameraActivity.prepareMediaRecorder(CameraActivity.java:534)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at es.anthorlop.camera.activities.CameraActivity.access$1000(CameraActivity.java:65)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at es.anthorlop.camera.activities.CameraActivity$7.onClick(CameraActivity.java:469)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.view.View.performClick(View.java:4469)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18790)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:808)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:103)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5331)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:832)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:648)
01-20 14:28:02.824 26986-26986/es.anthorlop.camera E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by shayzalman** [comment]
Same for me
The app crashes when I start to record (using LG G3)

**Comment by stefanionescu** [comment]
Did anyone find a solution?...

**Comment by whiteLT** [comment]
"Unsupported quality level: 8" - change source code. To different quality

**Comment by kkm** [comment]
CameraActivity.java
EDIT to
536 row `url_file = Environment.getExternalStorageDirectory().getPath() + "/" + timestamp + ".mp4";`
528 row `File file = new File(Environment.getExternalStorageDirectory().getPath() + "/");`

**Comment by vasanihardik** [comment]
comment this code
/*url_file = Environment.getExternalStorageDirectory().getPath() + "/" + timestamp + ".mp4";
528 row File file = new File(Environment.getExternalStorageDirectory().getPath() + "/");*/


try this one

File file_save = new File(Environment.getExternalStorageDirectory() + File.separator + "test.mp4");
        Log.e(TAG, " file-path " +file_save);

        mediaRecorder.setOutputFile(file_save.getPath());
